language: php

cache:
  directories:
    - $HOME/.composer/cache
    
sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  
before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer self-update
  - composer install

script:
  - phpunit --configuration travis.phpunit.xml.dist